### PR TITLE
Add IDeferredCatalog. Fixes #3

### PR DESCRIPTION
**Pull request by jamadden**

### CODE REVIEW

**Comment by jamadden** [comment]
@papachoco ?

**Comment by jamadden** [comment]
Thanks! Let me know if you need a release.

**Comment by papachoco** [comment]
Please ...  do so.. so I can start working on the migrations

**Comment by jamadden** [comment]
Done. 

But there shouldn't need to be much in the way of migrations immediately. For the time being, your existing implementations will work as they have been. When you're ready, you'll just change them to inherit from DeferredCatalog and delete their overrides of the base methods, and you can remove the special case in your indexing process.

**Comment by papachoco** [comment]
Thanks a lot.

Carlos

**Pull request merged**
