### PR TITLE
Add to the IMetadataCatalog interface the method force_unindex_doc which

### PR DESCRIPTION
**Pull request by papachoco**
implementer classes should override to remove a document from the index

### CODE REVIEW

**Comment by jamadden** [comment]
I don't understand the point of the `force_*` methods. What are they for? Why would anyone use them? If the answer is "the index is corrupted", the solution is "fix the problem that corrupted the index", not "add a band-aid method to workaround one problem at a time."

**Comment by jamadden** [comment]
Also, we can't add methods to existing interfaces without a major version bump (2.0), because existing objects would no longer comply with the interface.  The choices are either a new interface, or a major version bump. A new interface is often the better option.

**Comment by papachoco** [comment]
The 'force' method are simply calls to the super - class method. The reason behind is that we run the indexing process in a separate process where the doc_id/event is stored in redis first and then those events are pulled from redis and processed. These has allowed us to avoid index conflicts.

**Comment by papachoco** [comment]
I will add a new interface to implement the force_unindex so we don't have to do a major release bump

**Comment by papachoco** [comment]
All changes are in.

**Comment by jamadden** [comment]
Sorry, I don't understand how calling the super-class method lets you avoid index conflicts. 
The ZODB commits in sequential order and provides consistent views of objects as-of particular points in time (when the transaction begins), so that doesn't make much sense to me.  Can you be more specific or provide a code snippet demonstrating what you mean?

**Comment by papachoco** [comment]
```
@interface.implementer(IMetadataCatalog)
class MetadataRecorderCatalog(Catalog):

    super_index_doc = Catalog.index_doc

    def index_doc(self, docid, ob):
        pass

    def force_index_doc(self, docid, ob):
        self.super_index_doc(docid, ob)
```

**Comment by jamadden** [comment]
It actually doesn't make much sense to me why `IMetadataIndex` is even defined here. It doesn't extend more than one interface to join them together (the point of `INoAutoIndexEver`), it doesn't define any unique methods (aside from those under discussion here), it doesn't have an implementation here.

Perhaps we should declare it frozen (and semi-deprecated). Applications that are implementing it to do anything should instead define their own interface.

**Comment by papachoco** [comment]
So the normal index process does a no./op on the index operation

**Comment by papachoco** [comment]
A separate process (nti.metadata) does the following
```
def process_event(doc_id, event, ignore_errors=True):
    catalogs = metadata_catalogs()
    intids = component.getUtility(IIntIds)
    try:
        if event is REMOVED:
            for catalog in catalogs:
                catalog.unindex_doc(doc_id)
        else:
            ob = intids.queryObject(doc_id)
            if ob is None:
                logger.debug("Couldn't find object for %s", doc_id)
            elif isBroken(ob):
                logger.warn("Ignoring broken object with id %s", doc_id)
            else:
                for catalog in catalogs:
                    if IMetadataCatalog.providedBy(catalog):
                        catalog.force_index_doc(doc_id, ob)
                    else:
                        catalog.index_doc(doc_id, ob)
    except Exception:
        if ignore_errors:
            logger.exception("Error while indexing object with id %s", id)
        else:
            raise
```
reading the index events from redis

**Comment by papachoco** [comment]
```
@component.adapter(interface.Interface, IIntIdAddedEvent)
def _object_added(modeled, _):
       """
       put index event in redis
       ""'
        redis_queue_add(modeled)
```

**Comment by jamadden** [comment]
```python
@interface.implementer(IMetadataCatalog)
class MetadataRecorderCatalog(Catalog):
```

Oh, wow. That, umm, that looks pretty terrible. How is that necessary? Why is the regular `index_doc` defined to be a no-op? That seems to break the semantics of the interfaces it extends completely. 

If your problem is that you have an event listener that's firing when you don't want it to, then I suspect you don't want MetadataRecorderCatalog to be implementing the `IInjection` (and indeed, the `ICatalog`) interface in the first place (rather than defining broken implementations). Note that querying (`IIndexSearch` and `ICatalogQuery`) are separate interfaces, so code that needs to search shouldn't be looking for `ICatalog` it should be looking for one of those interfaces instead.

**Comment by papachoco** [comment]
Indeed we broke the interface; but it comes from moving the original nti.dataserver.metadata.index to this ''framework''.  We separated all of indexing event away to make transactions faster and avoid index contention. We still want to objects indexed but they are not critical to be indexed on the current transaction

**Comment by papachoco** [comment]
I do agree this interface does not belong in this pkg since it's very nti specific ; but there is already code that uses it.

**Comment by papachoco** [comment]
We'd like to move all this index ```framework``` to solr; but we are not there yet

**Comment by jamadden** [comment]
Right, we can't take it out (before a major version bump). We should just not extend or change it.

Does it make sense how I'm suggesting that you solve your problem? By using a different interface and *not* `ICatalog`? The interfaces that let you query are completely separate from the parts that define `index_doc`, so your object (that you don't want updating in the main transactions) should implement all the query interfaces but just not `ICatalog`...because `ICatalog` is what the event subscribers are registered on.

It would look like this:
```python
class IDeferredCatalog(ICatalogQuery, 
                                 ICatalogEdit, # [un]index_doc come from here
                                       zope.container.interfaces.IContainer):
    """A type of catalog that doesn't want to respond to subscriber events now."""

    zope.container.constraints.contains(ICatalogIndex)
```

`process_event` would then become simpler because it would just unconditionally call `index_doc`. `metadata_catalogs()` might need to make two component lookups, if it's currently looking for `ICatalog` (but if it looks for `ICatalogEdit` or `IInjection` instead, it wouldn't). Search code shouldn't need to change (unless it's not looking for `ICatalogQuery` but `ICatalog`).

I would support adding `IDeferredCatalog` as an interface to this package, because this package defines the event subscribers.

We could potentially even change `IMetadataCatalog` to be an alias for this new class. While technically that would require a major version bump, given the intent of what it was for, I could be convinced that doing so is actually a bug fix (the bug being that subscribers shouldn't be called for `IMetadataCatalog`), if that's compatible with the implementations (your implementation being the only extent one I know of).

**Comment by jamadden** [comment]
Since you have 
```python
@interface.implementer(IDeferredCatalog)
class MetadataRecorderCatalog(Catalog):
```

you'll find that MRCatalog still implements `ICatalog` because you extend `Catalog`. So you would need to use `interface.classImplementsOnly(MetadataRecorderCatalog, IDeferredCatalog, IAttributeAnnotatable, IIndexSearch)` to take that away.

Or we can slightly refactor catolog.py to introduce a base class:
```python
@implementer( #ICatalog NOPE
             IAttributeAnnotatable,
             zope.index.interfaces.IIndexSearch,
            )
class CatalogContainer(BTreeContainer):
   # current implementation goes here
   ...

@implementer(ICatalog)
class Catalog(CatalogContainer):
   pass
```

Which is probably what I would do. Let me know your thoughts on all this.

**Comment by papachoco** [comment]
Awesome .. thanks a lot Jason. ( this will be nice to have when we let professors start deleting courses - only nt-admin can can do now)

**Comment by jamadden** [comment]
OK, so I'll add IDeferredCatalog in the next couple days. Do you want `IMetadataIndex` to be an alias for it? That is, do you always defer writes in all implementations of `IMetadataIndex`, do all subclasses define `index_doc` as a no-op?

**Comment by papachoco** [comment]
Sounds good. Alias it's fine.

**Comment by papachoco** [comment]
Thx a lot. We just need the other two methods to unindex.  New interface?

**Comment by jamadden** [comment]
No, we don't need any different methods. You'll just call `index_doc` and `unindex_doc` (which are defined in IInjection).

**Pull request closed without merging**
